CENTRALITY_CLASS:
  - [0, 90]
CT_BINS: [2, 4, 6, 10, 14, 35]
PT_BINS: [2, 10]

BKG_MODELS: ["expo", "pol1", "pol2"]
BDT_EFFICIENCY: [0.10, 1., 0.01] # min, max ,step

TRAINING_DIR: "ls_training_opt"

TRAINING_PATHS:
  MC_PATH: /data/fmazzasc/PbPb_3body/pass3/tables/SignalTable_20g7.root
  BKG_PATH: /data/fmazzasc/PbPb_3body/pass3/tables/HypDataTable_ls.root

LOAD_APPLIED_DATA: False
APPLICATION_PATHS:
  DATA_PATH: /data/fmazzasc/PbPb_3body/pass3/tables/HypDataTable_data.root
  LS_PATH: /data/fmazzasc/PbPb_3body/pass3/tables/HypDataTable_ls.root
  LS_PION_PATH: 
  EM_PATH: 

ANALYSIS_RESULTS_PATH: /data/fmazzasc/PbPb_3body/pass3/analysis_results/AnalysisResults_data.root

XGBOOST_PARAMS:
  # general parameters
  n_jobs: 20 # number of available threads
  # learning task parameters
  objective: binary:logistic
  random_state: 42
  eval_metric: auc
  tree_method: hist

SIGMA_MC: True

HYPERPARAMS:
  max_depth: 13
  learning_rate: 0.09823
  n_estimators: 181
  gamma: 0.4467
  min_child_weight: 5.751
  subsample: 0.7447
  colsample_bytree: 0.5727
  seed: 42

HYPERPARAMS_RANGE: #TODO: check if it works without tuples
  # booster parameters
  max_depth: !!python/tuple [5, 20] # defines the maximum depth of a single tree (regularization)
  learning_rate: !!python/tuple [0.01, 0.3] # learning rate
  n_estimators: !!python/tuple [50, 500] # number of boosting trees
  gamma: !!python/tuple [0.3, 1.1] # specifies the minimum loss reduction required to make a split
  min_child_weight: !!python/tuple [1, 12]
  subsample: !!python/tuple [0.5, 0.9] # denotes the fraction of observations to be randomly samples for each tree
  colsample_bytree: !!python/tuple [0.5, 0.9] # denotes the fraction of columns to be randomly samples for each tree
  # # lambda: (0,10]  # L2 regularization term on weights
  # # alpha: (0,10]  # L1 regularization term on weight


TRAINING_COLUMNS:
- pt
- cos_pa
# - dca_de
# - dca_pr
# - dca_pi
- tpc_ncls_de
- tpc_ncls_pr
- tpc_ncls_pi
- tpc_nsig_de
- tpc_nsig_pr
- tpc_nsig_pi
- dca_de_pr
- dca_de_pi
- dca_pr_pi
# - cos_pa_lambda
# - mppi_vert
# - dca_lambda_hyper
- dca_de_sv
- dca_pr_sv
- dca_pi_sv
- chi2
# - cos_theta_ppi_H

